CompanyRegister/CompanyRegister/Models/Office.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CompanyRegister.Models
{
    public class Office
    {
        public Office()
        {
            this.Employees = new HashSet<Employee>();
        }

        [Key]
        public string Id { get; set; }

        public string Country { get; set; }

        public string City { get; set; }

        public string Street { get; set; }

        public int StreetNumber { get; set; }

        public bool Headquarter { get; set; }

        public Company Company { get; set; }

        public ICollection<Employee> Employees { get; set; }
    }
}

CompanyRegister/CompanyRegister/ViewModels/Offices/CompanyAllOfficesViewModel.cs
using System.Collections.Generic;

namespace CompanyRegister.ViewModels.Offices
{
    public class CompanyAllOfficesViewModel
    {
        public CompanyAllOfficesViewModel()
        {
            this.Offices = new List<CompanyOfficesViewModel>();
        }
        public string CompanyName { get; set; }

        public List<CompanyOfficesViewModel> Offices { get; set; }
    }
}

CompanyRegister/CompanyRegister/ViewModels/Offices/CompanyOfficesViewModel.cs
namespace CompanyRegister.ViewModels.Offices
{
    public class CompanyOfficesViewModel
    {
        public string Id { get; set; }

        public string CompanyName { get; set; }

        public string Country { get; set; }

        public string City { get; set; }

        public string Headquarter { get; set; }

        public int CountOfEmployees { get; set; }
    }
}

CompanyRegister/CompanyRegister/ViewModels/Offices/CreateOfficeInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace CompanyRegister.ViewModels.Offices
{
    public class CreateOfficeInputModel
    {
        public string Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string Country { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string City { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string Street { get; set; }

        [Required]
        [Range(0, 1000, ErrorMessage = "\"{0}\" must be number between {1} and {2}!")]
        [Display(Name = "Street Number")]
        public int StreetNumber { get; set; }

        public bool Headquarter { get; set; }
    }
}

CompanyRegister/CompanyRegister/ViewModels/Offices/DetailsOfficeViewModel.cs
namespace CompanyRegister.ViewModels.Offices
{
    public class DetailsOfficeViewModel
    {
        public string Id { get; set; }

        public string Country { get; set; }

        public string City { get; set; }

        public string Street { get; set; }

        public int StreetNumber { get; set; }

        public string Company { get; set; }

        public int NumberOfEmployees { get; set; }

        public string Headquarter { get; set; }
    }
}

CompanyRegister/CompanyRegister/ViewModels/Offices/EditOfficeInputViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CompanyRegister.ViewModels.Offices
{
    public class EditOfficeInputViewModel
    {
        public string Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string Country { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string City { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "\"{0}\" must be between {2} and {1} characters!")]
        public string Street { get; set; }

        [Required]
        [Range(0, 1000, ErrorMessage = "\"{0}\" must be number between {1} and {2}!")]
        [Display(Name = "Street Number")]
        public int StreetNumber { get; set; }

        public bool Headquarter { get; set; }       
    }
}

CompanyRegister/CompanyRegister/Controllers/OfficesController.cs
using CompanyRegister.Models;
using CompanyRegister.Services.Contracts;
using CompanyRegister.ViewModels.Offices;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CompanyRegister.Controllers
{
    public class OfficesController : Controller
    {
        private readonly ICompaniesService companiesService;
        private readonly IOfficesService officesService;

        public OfficesController(ICompaniesService companiesService, IOfficesService officesService)
        {
            this.companiesService = companiesService;
            this.officesService = officesService;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(CreateOfficeInputModel model)
        {           
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            
            Office office = new Office
            {
                Country = model.Country,
                City = model.City,
                Street = model.Street,
                StreetNumber = model.StreetNumber,
                Headquarter = model.Headquarter,                
            };

            Company company = this.companiesService.GetCompanyById(model.Id);
            
            if (office.Headquarter == true)
            {
                foreach (var currentOffice in company.Offices)
                {
                    if (currentOffice.Headquarter == true)
                    {
                        currentOffice.Headquarter = false;
                    }
                }
                company.Headquarter = office.City;
            }

            company.Offices.Add(office);
            this.companiesService.UpdateCompany(company);

            return this.RedirectToAction("Details", "Companies", new {@id = model.Id});
        }

        public IActionResult All(string id)
        {
            List<Office> offices = this.officesService.GettAllOffices(id).ToList();            
            Company company = this.companiesService.GetCompanyById(id);
            CompanyAllOfficesViewModel viewModel = new CompanyAllOfficesViewModel();

            viewModel.CompanyName = company.Name;

            foreach (var currentOffice in offices)
            {
                var office = new CompanyOfficesViewModel
                {
                    Id = currentOffice.Id,
                    CompanyName = company.Name,
                    Country = currentOffice.Country,
                    City = currentOffice.City,
                    Headquarter = currentOffice.Headquarter == true ? "YES" : "NO",
                    CountOfEmployees = currentOffice.Employees.Count()
                };

                viewModel.Offices.Add(office);                
            }

            return View(viewModel);
        }

        public IActionResult Details(string id)
        {
            Office office = this.officesService.GetOfficeById(id);

            if (office == null)
            {
                return this.View("NotFound");
            }

            DetailsOfficeViewModel officeVieModel = new DetailsOfficeViewModel
            {
               Id = office.Id, 
               Country = office.Country,
               City = office.City,
               Street = office.Street,
               StreetNumber = office.StreetNumber,
               Company = office.Company.Name,
               NumberOfEmployees = office.Employees.Count(),
               Headquarter = office.Headquarter == true ? "Yes" : "No"
            };

            return this.View(officeVieModel);
        }

        public IActionResult Edit(string id)
        {
            Office office = this.officesService.GetOfficeById(id);

            if (office == null)
            {
                return this.View("NotFound");
            }

            EditOfficeInputViewModel model = new EditOfficeInputViewModel
            {
                Id = office.Id,
                Country = office.Country,
                City = office.City,
                Street = office.Street,
                StreetNumber = office.StreetNumber,
                Headquarter = office.Headquarter                             
            };

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditOfficeInputViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            
            Office office = this.officesService.GetOfficeById(model.Id);
            Company company = this.companiesService.GetCompanyById(office.Company.Id);

            office.Country = model.Country;
            office.City = model.City;
            office.Street = model.Street;
            office.StreetNumber = model.StreetNumber;
            office.Headquarter = model.Headquarter;             

            if (model.Headquarter == true)
            {
                foreach (var currentOffice in company.Offices)
                {
                    if (currentOffice.Headquarter == true && currentOffice.Id != office.Id)
                    {
                        currentOffice.Headquarter = false;

                        this.officesService.UpdateOffice(currentOffice);
                    }
                }
                office.Company.Headquarter = office.City;
            }

            this.officesService.UpdateOffice(office);            

            return this.RedirectToAction("Details", new { @id = office.Id });
        }

        public IActionResult Delete(string id)
        {
            Office office = this.officesService.GetOfficeById(id);

            office.Company.Offices.Remove(office);

            if (office.Headquarter == true)
            {
                office.Company.Headquarter = null;
            }

            this.officesService.Delete(office);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

CompanyRegister/CompanyRegister/Views/Offices/All.cshtml
@model CompanyRegister.ViewModels.Offices.CompanyAllOfficesViewModel

@{
    ViewData["Title"] = "All";
}

<div class="text-center">
    <h3>@Model.CompanyName Offices</h3>
</div>

@{
    if (Model.Offices.Count() == 0)
    {
        <hr class="w-100" />
        <div class="text-center mt-3">
            <h2>There are no registered offices yet!</h2>            
        </div>
    }
    else
    {
        <table class="table mt-3">
            <thead>
                <tr class="row" style="background-color: peru">                    
                    <th scope="col" class="col-2 d-flex justify-content-center">Country</th>
                    <th scope="col" class="col-3 d-flex justify-content-center">City</th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Headquarter</th>
                    <th scope="col" class="col-3 d-flex justify-content-center">Number of employees</th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var office in Model.Offices)
                {
                <tr class="row" style="background-color: antiquewhite">                   
                    <td class="col-2 d-flex justify-content-center">
                        @office.Country
                    </td>
                    <td class="col-3 d-flex justify-content-center">
                        @office.City
                    </td>
                    <td class="col-2 d-flex justify-content-center">
                        @office.Headquarter
                    </td>
                    <td class="col-3 d-flex justify-content-center">
                        @office.CountOfEmployees
                    </td>
                    <td class="col-2 d-flex justify-content-center">
                        <a asp-controller="Offices" asp-action="Details" asp-route-id="@office.Id" class="btn btn-dark btn-sm mobile-fondsize-11">Details</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
}

CompanyRegister/CompanyRegister/Views/Offices/Create.cshtml
@model CompanyRegister.ViewModels.Offices.CreateOfficeInputModel

@{
    ViewData["Title"] = "Create";
}

<div class="h2 text-center text-dark font-weight-bold">Create Office</div>
<hr />
<div class="row justify-content-center text-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>          
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" placeholder="Country"/>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" placeholder="City"/>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" placeholder="Street"/>
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumber" class="control-label"></label>
                <input asp-for="StreetNumber" class="form-control" placeholder="Street Number"/>
                <span asp-validation-for="StreetNumber" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Headquarter" /> @Html.DisplayNameFor(model => model.Headquarter)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CompanyRegister/CompanyRegister/Views/Offices/Details.cshtml
@model CompanyRegister.ViewModels.Offices.DetailsOfficeViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="h2 text-center font-weight-bold text-dark">Office Details</div>
<hr class="w-50" />

<div class="row justify-content-center mt-5">
    <div class="col-md-6 card card-body bg-transparent shadow">
        <div class="row">
            <div class="col-md-6">
                <div><span class="font-weight-bold">Company Name: </span>@Model.Company</div>
                <div><span class="font-weight-bold">Office Employees: </span>@Model.NumberOfEmployees</div>
                <div><span class="font-weight-bold">Headquarter: </span>@Model.Headquarter</div>               
            </div>
            <div class="col-md-6">
                <div><span class="font-weight-bold">Country: </span>@Model.Country</div>
                <div><span class="font-weight-bold">City: </span>@Model.City</div>
                <div><span class="font-weight-bold">Street: </span>@Model.Street</div>
                <div><span class="font-weight-bold">Street №: </span>@Model.StreetNumber</div>
            </div>
        </div>
        <hr />
        <div class="d-flex justify-content-around mt-1">
            <a asp-area="" asp-controller="Offices" asp-action="Edit" asp-route-id="@Model.Id"
               class="btn" style="background-color:peru">
                <span class="text-white ml-1 mr-2"><i class="fas fa-edit ml-1"></i> Edit</span>
            </a>
            <a asp-area="" asp-controller="Offices" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn" style="background-color:darkred" onclick="return  confirm('Are you sure you want to delete office: @Model.City')">
                <span class="text-white"><i class="fas fa-trash"></i> Delete</span>
            </a>
        </div>
    </div>
</div>

CompanyRegister/CompanyRegister/Views/Offices/Edit.cshtml
@model CompanyRegister.ViewModels.Offices.EditOfficeInputViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="h2 text-center text-dark font-weight-bold">Create Office</div>
<hr />
<div class="row justify-content-center text-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumber" class="control-label"></label>
                <input asp-for="StreetNumber" class="form-control" />
                <span asp-validation-for="StreetNumber" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Headquarter" /> @Html.DisplayNameFor(model => model.Headquarter)
                </label>
            </div>                       
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}